// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef MainWindowUI_h
#define MainWindowUI_h

#include <FL/Fl.H>

void make_window( );

#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Menu_Bar.H>

#include "GLWindow2d.h"
#include "GLWindow3d.h"

class MainWindowUI {
	public:
		MainWindowUI( );

		Fl_Double_Window    * mainWindow;
		Fl_Button           * startButton;
		Fl_Button           * clearButton;
		Fl_Text_Display     * output;
		GLWindow3d            * glWindow3d;
		GLWindow2d            * glWindow2d;
		Fl_Menu_Bar         * menuBar;
		static Fl_Menu_Item menu_menuBar[];
		static Fl_Menu_Item * statesMenu;

		void dummy( );

};

#endif
