/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TempCalcJava */

#ifndef _Included_TempCalcJava
#define _Included_TempCalcJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TempCalcJava
 * Method:    initializeTemperature
 * Signature: ([DIIDDDD)V
 */
JNIEXPORT void JNICALL Java_TempCalcJava_initializeTemperature
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     TempCalcJava
 * Method:    evolveTemperature
 * Signature: ([DIIDDDDDD[D)V
 */
JNIEXPORT void JNICALL Java_TempCalcJava_evolveTemperature
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif